
GET http://localhost:3000/api/auth
Content-Type: application/json 

###
POST http://localhost:3000/api/user/new
Content-Type: application/json 

{
 "firstName": "God'sgift",  
 "middleName": "Matthew",
 "lastName": "Uko",   
 "email": "example@gmail.com",
 "password": "dhbbdhdhhddh.1234GO!",
 "phone": "+2349071046909"
}

###
POST http://localhost:3000/api/auth
Content-Type: application/json 

{  
 "email": "giftee@gmail.com",
 "password": "qwerty1234GO!" 
}