GET http://localhost:3000/api/farm/eggorand
Content-Type: application/json

###

POST http://localhost:3000/api/farm/new
Content-Type: application/json

{
    "name": "Eggorand",
    "ownerName": "Uko, God'sgift Matthew",
    "contact": "+2349071046909",
    "description": "This is an egg farm",
    "category": "livestock"
}


###

POST http://localhost:3000/api/farm/new
Content-Type: application/json

{
    "name": "Eggorand",
    "ownerName": "Uko, God'sgift Matthew",
    "contact": "+2349071046909",
    "description": "This is an egg farm",
    "category": "livestock",
    "postalCode": "52060",
    "street": "Nduk street",
    "city": "Uyo",
    "state": "Akwa Ibom",
    "country": "Nigeria"
}
