@host=localhost:3000
@api_route=http://{{host}}/api
@user_route={{api_route}}/user
@farm_route={{api_route}}/farm
@content_type=application/json
@bearer_token={{bearerToken}}

DELETE  {{farm_route}}/eggorand
Content-Type: {{content_type}}
Authorization: {{bearer_token}}
###

POST {{farm_route}}/new
Content-Type: {{content_type}}
Authorization: {{bearer_token}}

{
    "name": "Eggorand",
    "description": "This is an egg farm",
    "category": "liv",
    "contact": "08097303617"
}


###
# POST {{farm_route}}/new
# Content-Type: {{content_type}}
# Authorization: {{bearer_token}}

# {
#     "name": "Eggorand",    
#     "ownerName": "Uko, God'sgift Matthew",  
#     "contact": "+2349071046909",
#     "description": "This is an egg farm",
#     "category": "livestock",
#     "postalCode": "52060",
#     "street": "Nduk street",
#     "city": "Uyo",
#     "state": "Akwa Ibom",
#     "country": "Nigeria"
# }

###
GET {{farm_route}}/Millland
Content-Type: {{content_type}}
Authorization: {{bearer_token}}

###
GET {{farm_route}}/all
Content-Type: {{content_type}}
Authorization: {{bearer_token}}

###