@host=localhost:3000
@api_route=http://{{host}}/api
@user_route={{api_route}}/user
@content_type=application/json
@bear_token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwicm9sZSI6Im5vcm1hbCIsImlhdCI6MTY2MzA4NzU5NiwiZXhwIjoxNjYzMjYwMzk2fQ.H2Zw2MYBQlGAdaz29VL0P9A5AQq1wPvVIsj0D6LTtsU

###
GET {{api_route}}/ping
Content-Type: {{content_type}} 
###

POST {{user_route}}/new
Content-Type: {{content_type}} 

{
 "firstName": "God'sgift",   
 "middleName": "Matthew",   
 "lastName": "Uko",
 "email": "gifty@gmail.com",
 "password": "abc1234GO!"
}

###
GET {{user_route}}/all  
Content-Type: {{content_type}} 
Authorization: {{bear_token}}

###
GET {{user_route}}/gift@gmail.com
Content-Type: {{content_type}} 
Authorization: {{bear_token}}

###
PUT {{user_route}}/giftee@gmail.com
Content-Type: {{content_type}} 
Authorization: {{bear_token}}

{
    "email": "giftee@gmail.com"
}

###
DELETE {{user_route}}/gifty@gmail.com
Content-Type: {{content_type}} 
Authorization: {{bear_token}}