
@user_route={{apiHost}}/user
@contentType=application/json
# @bearer_token=Bearer {{login.response.body.data.token}}
@bearer_token={{bearerToken}}

###
GET {{apiHost}}/ping
Content-Type: {{contentType}} 
###

# @name login
POST {{apiHost}}/auth
Content-Type: {{contentType}} 

{  
 "email": "gifty@gmail.com",
 "password": "{{user_password}} "
} 

### Admin
POST {{apiHost}}/auth
Content-Type: {{contentType}} 

{  
 "email": "admin@farmassist.ng",
 "password": "{{admin_pass}}" 
}

###
POST {{user_route}}/new
Content-Type: {{contentType}} 

{
 "firstName": "God'sgift",   
"middleName": "Matthew",       
 "lastName": "Uko",
 "email": "gifty@gmail.com",
 "password": "abc1234GO!"
}

###
GET {{user_route}}/all
Content-Type: {{contentType}} 
Authorization: {{bearer_token}}

###
GET {{user_route}}/gifty@gmail.com
Content-Type: {{contentType}} 
Authorization: {{bearer_token}}

###
PUT {{user_route}}/gifteee@gmail.com
Content-Type: {{contentType}} 
Authorization: {{bearer_token}}

{
 "email": "gifteee@gmail.com"
}

###
DELETE {{user_route}}/gifty@gmail.com
Content-Type: {{contentType}} 
Authorization: {{bearer_token}}