
GET http://localhost:3000/api/ping
Content-Type: application/json 


###

POST http://localhost:3000/api/user/new
Content-Type: application/json 

{
 "firstName": "God'sgift",   
 "middleName": "Matthew",   
 "lastName": "Uko",   
 "email": "example@gmail.com",
 "password": "1234sweee"
}

###
GET http://localhost:3000/api/user/all  
Content-Type: application/json 


###
GET http://localhost:3000/api/user/example@gmail.com
Content-Type: application/json 


###
PUT http://localhost:3000/api/user/gift@gmail.com
Content-Type: application/json 

{
    "gender": "male"
}