name: Deploy Script

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            # move to project directory
            cd ${{ secrets.PATH }} && \
            # upload new ENV
            echo "${{secrets.ENV}}" > .env && \
            # install yarn packages
            yarn && yarn run build && yarn run migration:run && yarn run start:staging
            # remove git folders
            rm -rf .git && \
            rm -rf .github && \
            cd ~  && \
            rm -rf .github
